services:
  chemist-flow:
    container_name: chemist-flow
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - CHEMIST_FLOW_HOST
      - CHEMIST_FLOW_PORT
    stdin_open: true
    tty: true
