name: Scala CI

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "**/*.txt"
      - "**/*.sh"
      - "examples/**"
      - "migrations/**"
      - "scripts/**"
      - "Dockerfile*"
      - "docker*"
  pull_request:
    branches: ["master"]
    paths-ignore:
      - "**/*.txt"
      - "**/*.sh"
      - "examples/**"
      - "migrations/**"
      - "scripts/**"
      - "Dockerfile*"
      - "docker*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: "sbt"

      - name: Cache sbt dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Check for Scala format violations
        run: sbt scalafmtCheckAll

      - name: Build and test with sbt
        run: sbt clean compile test
